SXFNSWXZAI-236 / GENs are not used in usernames
DataShades/ckanext-saml2 pull request #60
Opened 2017-05-15 13:29 UTC by wildcatzita

2017-05-17 06:04 UTC, smotornyuk requested changes

2017-05-17 06:04 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +    print 'context = {0}, data_dict = {1}'.format(context, data_dict)
?

2017-05-17 06:04 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +        from ckan.logic.action.delete import user_delete as ckan_user_delete
Do you have any particular reason to avoid top level import?

2017-05-17 06:04 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +            data_dict['name'] = username
I've asked you before. On L376 username is used to obtain user from db. If you are generating the save value - why don't you use same variable as well.
If it different values - L376 unable to finde you new user in feature, right? and you end up creating infinite amount of users

2017-05-17 06:04 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +            return model.User.get(username)
Why you duplicate return ? It happens little bit below

2017-05-17 06:04 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +    if query is not None:
So, only users with GEN can be deleted. Are you sure, that there will be no any common users, provided not by SSO

2017-05-18 07:11 UTC, smotornyuk requested changes

2017-05-18 07:11 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +def saml2_get_user_by_name_id(id=None):
It looks like you return user's id, not user itself. You need little bit more prominent names

2017-05-18 07:11 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +def saml2_get_user_by_name_id(id=None):
And why somebody may call your function without `id` ? I think that this argument should be required

2017-05-18 07:11 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +    query = model.Session.query(SAML2User).\
Let's continue with naming problems. This is not query - this is result of query, - user info

2017-05-18 07:11 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +    return query.id if query is not None else query
`query.id if query else None` ?

2017-05-18 07:11 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +def saml2_get_user_info(id=None, return_name_id=False):
Once again, why arguments are optional?

2017-05-18 07:11 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +        return query if query is None else query.name_id
Why your returns are so inconsistent? :volcano:

2017-05-18 07:11 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +def saml2_get_user_info(id=None, return_name_id=False):
`return_name_id` seems absolutely redundant... Could you remove it?

2017-05-18 07:11 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +        if data_dict.get('nameid'):
how about `and`?

2017-05-18 07:11 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +                data_dict['id'] = saml2_user
as i mentioned above - say explicitly, that you use user's id, not user object

2017-05-18 07:11 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +    logic.check_access('user_delete', context, data_dict)
a thought, CKAN will check access to `user_delete` inside action itself.

2017-05-18 07:11 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +        return query
Wouldn't it be much better to return model object, not query?

2017-05-18 07:11 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +        query = saml2_get_user_info(c.user).first()
1. It's not a query, it user_info!
2. Just return user_info from this function, i do not think that you win something by manual call to `first` here

2017-05-18 07:11 UTC, smotornyuk commented on ckanext/saml2/tests/__init__.py
> +
Do you testing something?

2017-05-18 11:34 UTC, wildcatzita commented on ckanext/saml2/plugin.py
> +    if return_name_id:
I leave if for output user name_id in template

2017-05-18 11:35 UTC, wildcatzita commented on ckanext/saml2/plugin.py
> +        return query
I leave it for using query.update instead of making new query for update custom table.

2017-05-24 02:00 UTC, MrkGrgsn commented on ckanext/saml2/plugin.py
> +            c.user = user_info.user_name
Following on from my comment on the Jira ticket. The pattern used on this line causes problems when the username is changed.  It should take the user id from the saml2_user table and subsequently get the current username from the user table, alternatively `saml2_get_user_info()` could be modified to join user and saml2_user tables and return the complete and accurate user info.

2017-05-25 09:30 UTC, closed without merging