SXFNSWXZAI-238 / Fix for user_edit_form template
DataShades/ckanext-saml2 pull request #64
Opened 2017-05-22 10:28 UTC by wildcatzita

2017-05-23 04:53 UTC, smotornyuk requested changes

2017-05-23 04:53 UTC, smotornyuk commented on ckanext/saml2/templates/user/edit_user_form.html
> +{% endif %}
Try to avoid nested if-blocks and use `asbool` helper(i belive, that it already available in CKAN>2.4)

2017-05-23 05:01 UTC, smotornyuk requested changes

2017-05-23 05:01 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +        c.allow_user_changes = config.get('ckan.saml2.allow_user_changes', False)
not consistent behavior - you'll get string, when this directive defined and boolean, when it does not. Use converters to boolean

2017-05-23 05:01 UTC, smotornyuk commented on ckanext/saml2/templates/user/edit_user_form.html
> +                    {{ form.checkbox("user_custom_profile_data_checkbox", id="user_custom_profile_data_checkbox", label="I want to provide custom profile data", value=c.is_allow_update, classes=["use
"user_custom_profile_data_checkbox" - get rid of **_checkbox**

2017-05-23 05:01 UTC, smotornyuk commented on ckanext/saml2/plugin.py
> +            logic.tuplize_dict(logic.parse_params(request.params))))
Are you sure, that you have no access to `request.POST` ? This construction is quite cumbersome

2017-05-29 12:15 UTC, smotornyuk approved these changes

2017-06-05 03:17 UTC, MrkGrgsn commented
I'm not particularly happy with this code. It works but it's hard to read and sort of messy but we've run out of time; cleaning up will have to happen in future.

2017-06-05 03:17 UTC, merged